services:
  imageprojectbackend:
    image: ${DOCKER_REGISTRY-}image-archive-api
    build:
      context: src/api
      dockerfile: Dockerfile

  imageprojectfrontend:
    image: ${DOCKER_REGISTRY-}image-archive
    build:
      context: src/frontend
      dockerfile: Dockerfile