secrets:
  image_archive_ca_cert:
    file: ${USERPROFILE}/source/secrets/image-archive-ca.crt
  image_archive_api_cert:
    file: ${USERPROFILE}/source/secrets/image-archive-api.pfx

volumes:
  sqlvolume:

services:
  dev_db:
    container_name: dev_db
    profiles: [dev]
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: missing
    env_file: ${USERPROFILE}/source/secrets/dev_db.env
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped
    ports:
      - "127.0.0.1:1433:1433"

  dev_api:
    container_name: dev_api
    profiles: [dev]
    image: ${DOCKER_REGISTRY-}image-archive-api
    build:
      context: .
      dockerfile: src/api/Dockerfile
      no_cache: true
      pull: true
    depends_on:
      - dev_db
    secrets:
      - source: image_archive_ca_cert
        target: /usr/local/share/ca-certificates/image-archive-ca.crt
      - source: image_archive_api_cert
        target: /https/image_archive_api_cert.pfx
    env_file: ${USERPROFILE}/source/secrets/dev_api.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ${USERPROFILE}/source/images:/app/images
      - ${USERPROFILE}/source/archives:/app/archives
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  dev_frontend:
    container_name: dev_frontend
    profiles: [dev]
    image: ${DOCKER_REGISTRY-}image-archive
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
      no_cache: true
      pull: true
    depends_on:
      - dev_api
    secrets:
      - source: image_archive_ca_cert
        target: /usr/local/share/ca-certificates/image-archive-ca.crt
    env_file: ${USERPROFILE}/source/secrets/dev_frontend.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro