secrets:
  image_archive_ca_cert:
    file: /Users/nathanmichelotti/source/secrets/image-archive-ca.crt
  image_archive_api_cert:
    file: /Users/nathanmichelotti/source/secrets/image-archive-api.pfx
  image_archive_api_cert_pw:
    file: /Users/nathanmichelotti/source/secrets/image-archive-api-cert-pw.txt

volumes:
  sqlvolume:

services:
  dev_db:
    container_name: dev_db
    profiles: [dev]
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file: /Users/nathanmichelotti/source/secrets/dev_db.env
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped
    ports:
      - "127.0.0.1:1433:1433"

  dev_api:
    container_name: dev_api
    profiles: [dev]
    image: ${DOCKER_REGISTRY-}image-archive-api
    build:
      context: src/api
      dockerfile: Dockerfile
    depends_on:
      - dev_db
    secrets:
      - source: image_archive_ca_cert
        target: /usr/local/share/ca-certificates/image-archive-ca.crt
      - source: image_archive_api_cert
        target: /https/image_archive_api_cert.pfx
    env_file: /Users/nathanmichelotti/source/secrets/dev_api.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /Users/nathanmichelotti/source/Images:/app/Images
      - /Users/nathanmichelotti/Library/Application Support/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - /Users/nathanmichelotti/Library/Application Support/ASP.NET/Https:/home/app/.aspnet/https:ro

  dev_frontend:
    container_name: dev_frontend
    profiles: [dev]
    image: ${DOCKER_REGISTRY-}image-archive
    build:
      context: src/frontend
      dockerfile: Dockerfile
    depends_on:
      - dev_api
    secrets:
      - source: image_archive_ca_cert
        target: /usr/local/share/ca-certificates/image-archive-ca.crt
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - /Users/nathanmichelotti/Library/Application Support/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - /Users/nathanmichelotti/Library/Application Support/ASP.NET/Https:/home/app/.aspnet/https:ro
