namespace frontend.Models;

public class CameraPositionEntry
{
    public string SiteName { get; set; } = string.Empty;
    public int SiteNumber { get; set; }
    public string PositionName { get; set; } = string.Empty;
    public int Value { get; set; }
}
public class CameraPositions
{
    public static readonly List<CameraPositionEntry> Positions = new()
    {
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Mason Valley", Value = 11 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Sawtooth Ridge", Value = 12 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Sweetwater Range", Value = 13 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "White Mountain Range", Value = 14 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Walker River", Value = 15 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Corey Peak", Value = 16 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Mt Grant", Value = 17 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "North Aspect", Value = 18 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "South Aspect", Value = 19 },
        new CameraPositionEntry { SiteName = "Rockland", SiteNumber = 1, PositionName = "Mt Rose", Value = 20 },

        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Angel Peak", Value = 14 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Refuge HQ", Value = 15 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 1, PositionName = "Vegetation Interspace", Value = 16 },

        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "LV Precip Gage", Value = 14 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Angel Peak", Value = 15 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Hayford Peak", Value = 16 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Sheep 3&4", Value = 17 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 2, PositionName = "Canopy Interspace", Value = 18 },

        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "Runoff Collector", Value = 14 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "NRCS SCAN Site", Value = 15 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 3, PositionName = "LV Precip Station", Value = 16 },

        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Rain Gage", Value = 14 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Canopy Interspace", Value = 15 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "Sap Flow Sensors", Value = 16 },
        new CameraPositionEntry { SiteName = "Sheep", SiteNumber = 4, PositionName = "PIMO Canopy", Value = 17 },

        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 0, PositionName = "North West", Value = 8 },

        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 1, PositionName = "North West", Value = 8 },

        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 2, PositionName = "North West", Value = 8 },

        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Snow Pole 1", Value = 14 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Snow Pole 2", Value = 15 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Mountain Mahogony Canopy", Value = 16 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Spring 1", Value = 17 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 3, PositionName = "Cave Mountain", Value = 18 },

        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Snow Pole", Value = 14 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Snow Weighing Sensors (Shade)", Value = 15 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Snow Weighing Sensors (Sun)", Value = 16 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Bristlecone Canopy", Value = 17 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "Limber Pine Canopy", Value = 18 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "South Spring Valley", Value = 19 },
        new CameraPositionEntry { SiteName = "Spring", SiteNumber = 4, PositionName = "South Schell Creek Range", Value = 20 },

        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "UNLV Data Logger", Value = 14 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 1, PositionName = "Great Basin National Park", Value = 15 },

        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "Precipitation Gauge", Value = 13 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "Great Basin Ranch Exhibit", Value = 14 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 2, PositionName = "Spring One", Value = 15 },

        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "North West", Value = 8 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Solar Panels", Value = 9 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Tower Base", Value = 10 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Site Access", Value = 11 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Soil Sensors", Value = 12 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Sap Flow Sensors", Value = 13 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Vegetation Interspace", Value = 14 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Deciduous Leaves", Value = 15 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Soil Sensors", Value = 16 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Snow Weighing Sensor", Value = 17 },
        new CameraPositionEntry { SiteName = "Snake", SiteNumber = 3, PositionName = "Snow Depth Pole", Value = 18 },

        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "North", Value = 1 },
        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "North East", Value = 2 },
        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "East", Value = 3 },
        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "South East", Value = 4 },
        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "South", Value = 5 },
        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "South West", Value = 6 },
        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "West", Value = 7 },
        new CameraPositionEntry { SiteName = "Eldorado", SiteNumber = 3, PositionName = "North West", Value = 8 },
    };
}

